project:
  type: website
  output-dir: docs

website:
  title: "skimpy"
  navbar:
    type: dark
    background: primary
    left:
      - href: index.ipynb
        text: Home
      - href: contributing.md
        text: Contributing

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
